// Independent reader for Zclassic v2.1.2-beta6's documented CCoins format.
// Reference: src/{coins.h,compressor.cpp,chain.h,txdb.cpp,chainparams.cpp} at that tag.
import {createHash,ECDH} from 'node:crypto';
export const sha256=b=>createHash('sha256').update(b).digest();
export const hash256=b=>sha256(sha256(b));
export class Reader {
  constructor(bytes){this.bytes=Buffer.from(bytes);this.offset=0;}
  read(n){if(!Number.isSafeInteger(n)||n<0||this.offset+n>this.bytes.length)throw Error('Truncated record');const b=this.bytes.subarray(this.offset,this.offset+n);this.offset+=n;return b;}
  byte(){return this.read(1)[0];}
  varbig(){let n=0n;for(let i=0;i<10;i++){const c=this.byte();n=n*128n+BigInt(c&127);if(n>0xffffffffffffffffn)throw Error('Varint overflow');if(!(c&128))return n;n++;}throw Error('Varint too long');}
  varint(){const n=Number(this.varbig());if(!Number.isSafeInteger(n))throw Error('Varint overflow');return n;}
  compact(){const c=this.byte();if(c<253)return c;const n=c===253?this.read(2).readUInt16LE():c===254?this.read(4).readUInt32LE():Number(this.read(8).readBigUInt64LE());if(!Number.isSafeInteger(n))throw Error('Compact size overflow');if(n<(c===253?253:c===254?65536:2**32))throw Error('Noncanonical compact size');return n;}
}
export function varint(n){if(!Number.isSafeInteger(n)||n<0)throw Error('Invalid varint');const a=[n&127];while(n>127){n=Math.floor(n/128)-1;a.unshift((n&127)|128);}return Buffer.from(a);}
export function compact(n){if(n<253)return Buffer.from([n]);const b=Buffer.alloc(n<=65535?3:5);b[0]=b.length===3?253:254;b.length===3?b.writeUInt16LE(n,1):b.writeUInt32LE(n,1);return b;}
export function amount(value){let x=BigInt(value);if(x===0n)return 0n;x--;const exponent=x%10n;x/=10n;const n=exponent<9n?(x/9n)*10n+(x%9n)+1n:x+1n;return n*10n**exponent;}
function script(r){const type=r.varint();if(type===0)return Buffer.concat([Buffer.from('76a914','hex'),r.read(20),Buffer.from('88ac','hex')]);if(type===1)return Buffer.concat([Buffer.from('a914','hex'),r.read(20),Buffer.from('87','hex')]);if(type>=2&&type<=5){let pub=Buffer.concat([Buffer.from([type<4?type:type-2]),r.read(32)]);if(type>=4)pub=ECDH.convertKey(pub,'secp256k1',undefined,undefined,'uncompressed');return Buffer.concat([Buffer.from([pub.length]),pub,Buffer.from([0xac])]);}if(type-6>10000)throw Error('Oversized script');return r.read(type-6);}
export function coins(bytes){const r=new Reader(bytes),version=r.varint(),code=r.varint();const live=[Boolean(code&2),Boolean(code&4)];let nonzero=Math.floor(code/8)+((code&6)?0:1);while(nonzero){const mask=r.byte();if(mask)nonzero--;for(let bit=0;bit<8;bit++)live.push(Boolean(mask&(1<<bit)));if(live.length>100000)throw Error('Output mask too large');}const outputs=[];for(let index=0;index<live.length;index++)if(live[index])outputs.push({index,value:amount(r.varbig()),script:script(r)});const height=r.varint();if(r.offset!==r.bytes.length)throw Error('Trailing coin data');return {version,height,coinbase:Boolean(code&1),outputs};}
const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function address(script){let prefix,payload;if(script.length===25&&script.subarray(0,3).equals(Buffer.from('76a914','hex'))&&script.subarray(23).equals(Buffer.from('88ac','hex'))){prefix=Buffer.from('1cb8','hex');payload=script.subarray(3,23);}else if(script.length===23&&script.subarray(0,2).equals(Buffer.from('a914','hex'))&&script[22]===0x87){prefix=Buffer.from('1cbd','hex');payload=script.subarray(2,22);}else if(((script.length===35&&script[0]===33)||(script.length===67&&script[0]===65))&&script.at(-1)===0xac){const pub=script.subarray(1,-1);if(!((pub.length===33&&(pub[0]===2||pub[0]===3))||(pub.length===65&&pub[0]===4)))return null;try{ECDH.convertKey(pub,'secp256k1');}catch{return null;}prefix=Buffer.from('1cb8','hex');payload=createHash('ripemd160').update(sha256(pub)).digest();}else return null;const body=Buffer.concat([prefix,payload]);let n=BigInt('0x'+Buffer.concat([body,hash256(body).subarray(0,4)]).toString('hex')),out='';while(n){out=alphabet[Number(n%58n)]+out;n/=58n;}return out;}
export function serializedOutput(output){const value=Buffer.alloc(8);value.writeBigInt64LE(output.value);return Buffer.concat([varint(output.index+1),value,compact(output.script.length),output.script]);}
export function block(bytes){const r=new Reader(bytes);r.varint();const height=r.varint(),status=r.varint();r.varint();if(status&24)r.varint();if(status&8)r.varint();if(status&16)r.varint();if(status&128)r.read(4);r.read(32);const start=r.offset;r.read(4);const prev=Buffer.from(r.read(32));r.read(64);const time=r.read(4).readUInt32LE();r.read(36);const size=r.compact();if(size>2000)throw Error('Invalid header solution length');r.read(size);const hash=hash256(r.bytes.subarray(start,r.offset));return {height,prev,time,hash};}
